### ISSUE TITLE
Better referral

### ISSUE THREAD

**Issue by coolweddin** [Ctrlpanel-gg/panel#1001]
### Feature Description

Hey, in the partner referral system you can only set % to give coins to customer and partner, and on the normal you can say that the user how invites someone gets something, but you can’t say, that the invited one gets coins, pls add this

### Solution Idea

Add, that you can change in the partner system between % and coins, and also add an field in partner, where you can say,how much coins invited one should get, if you want % and coins.
Add in the normal referral, that you can say, how much coins the invited should get, so it’s like an coupon, if I’m at coupons, pls add an extra site to reedem, my user often don’t find it.

**Comment by S0ly** [comment]
I'm sorry but we dont understand what you mean its a little bit difficult to read

**Comment by OddDevelopment** [comment]
> I'm sorry but we dont understand what you mean its a little bit difficult to read could you explain simpler ?

I think they are asking for a way to make it so you can do a set value of coins instead of a % of sales for partners who refer users (probably on a per register basis, ie every person who uses the code the partner gets x amount of coins) and a set amount of coins to give the user who registered with a partner code.

**Comment by S0ly** [comment]
no explanation for too long sorry :/

**Comment by coolweddin** [comment]
Sorry, lost my login
