### ISSUE TITLE
[Feature] Basket on checkout

### ISSUE THREAD

**Issue by GeckoBoy84** [Ctrlpanel-gg/panel#871]
### Feature Description

Currently every purchase is it’s own transaction resulting in more fees being paid than necessary.

### Solution Idea

Add a basket, or some form of way to purchase multiple items at once, in one transaction.

**Comment by IceToast** [comment]
Since fees and taxes are calculated in percentage, it doesn't matter. However it also doesn't make sense on how the shop works atm. You have products that give you x amount of credits (and in rare cases there are products that can give you a higher server limit). If you need more than x credits just choose a product of a higher tier.

**Comment by GeckoBoy84** [comment]
There is a minimum cut off for fees resulting in a flat fee making you lose more.

**Comment by 1day2die** [comment]
Wont be added. It's really not needed with the way our Shop System works right now. As ice said, just choose a higher credits package. The benefits of this are way lower than the efford to code it

**Comment by IceToast** [comment]
Again it doesn't make sense on our shop system implementation. What your payment fee on single payments is doesn't really matter in this case. It would need a whole shop rebuilt to build it from scratch. 

However that is not in scope and not planned rn as it works just fine for how ctrlpanel works atm.
