### ISSUE TITLE
[Feature] Discord role on purchase

### ISSUE THREAD

**Issue by GeckoBoy84** [Ctrlpanel-gg/panel#872]
### Feature Description

Currently users get a discord role when linking their discord.

### Solution Idea

Another option for a different role given to people that purchase from the store.

**Comment by purejosh** [comment]
This is a big need. Especially because no purchase is needed to get the default role, so it's hard to tell who's an actual paying client and who's just existing. 

Could these roles be set up in a few different ways? Such as "current subscriber" for those with at least one active server, "suspended" for those who's credits have run out, and maybe even something like "power user" for those with x+ servers (x being configurable) active.

**Comment by S0ly** [comment]
+1 I might do it
