### ISSUE TITLE
[Feature] A way to register/login with discord or google

### ISSUE THREAD

**Issue by OddsGames** [Ctrlpanel-gg/panel#889]
### Feature Description

When you are logging in or signing up there is an option for registering/logging in with Google, this would also make it easy to do email verification because with Google you would know they own the email.

### Solution Idea

Add a button on the register and login page for signing in with Google or discord

**Comment by GeckoBoy84** [comment]
This will not be added as per the discord server:
We don’t have discord auth added as a login method because pterodactyl doesn’t have this either. Currently, our registration form automatically sends data to pterodactyl as well. So you get one login for both panels.
If we were to add discord login to our login form, you would still need to log in to pterodactyl.
This can be done using an ugly password generator on CtrlPanel. But this, kind of, still defeats the purpose of the convenient discord login since you still need to log in. 
Adding discord login to pterodactyl also requires extra work since I assume you don’t want random people to log into your pterodactyl panel while they haven’t registered on CtrlPanel yet (or are even banned from your CtrlPanel).
Because of this, we chose to have a standard login form linked to pterodactyl.

**Comment by AGuyNamedJens** [comment]
As Gecko said; We can't add the feature unless we also modify the way we connect to Pterodactyl, which also includes security risks (as we're open source, what could possibly go wrong with generating random passwords and people finding an exploit in our source code without reporting it?).

However feel free to ask/create a bounty in the Discord server to let someone make it if you'd really want the feature. We're unfortunately not going to be supporting this in the main panel.
