### ISSUE TITLE
[Bug]: Visual : smtp passwords viewable in settings

### ISSUE THREAD

**Issue by kenshin133** [Ctrlpanel-gg/panel#897]
### What is your request about?

In mail settings it looks like this password is no longer "hidden" once entered posing some kind of security risk ig. 

![image](https://github.com/Ctrlpanel-gg/panel/assets/29851415/3f3cef85-0dff-46d8-ba85-d11e15d8be3e)

Additionally this might be a goood place to consider changing the APIkeys to be hidden by default, since anyone who can get to settings can copy/paste api keys (and smtp password) 

### Branch

development

**Comment by 1day2die** [comment]
idk if this is something we should adress. after all, the permissions make it very easy to hide the whole section from users who shouldnt see it.

anyone who does see it, can just change the HTML in their browser to change the field from "password" to "text" and reveal the "hidden" password this way

**Comment by 1day2die** [comment]
@IceToast

**Comment by kenshin133** [comment]
well, the larger issue I think is that its transmitting the password when this page is requested. I could be wrong but I assumed it should not do that, instead only returning "******" (regardless of the type of text box it is). if you input a new password it would of course compare them on the backend. This again was just an assumption, but since its only displaying a value and not actually being used to authenticate anything is there any reason to reference the password?

perhaps im mistaken.

**Comment by IceToast** [comment]
Yes you are mistaken in this regard. "*****" Fields are always client side hidden. Meaning that the real input data is always visible to the browser in its HTML or JS Code. 
However it's a good point, fields could get a hidden parameter which may result in a slightly better end user experience. Since it's only viewable by users/admins with permissions to do so, it's not a security regard.
